name: test1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - pandas=1.3.4
  - pip:
      - rpaframework==11.4.0
      # robotframework-datadriver added here:
      - robotframework-datadriver==1.4.1